name: CI

on:
  push:
    branches:
      - 'main'
      - 'release-v**'
      - 'full-sonar-analysis-**'
  pull_request:

jobs:
  build:
    name: Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout powsybl-core reporter branch
        uses: actions/checkout@v4
        with:
          repository: powsybl/powsybl-core
          ref: refs/heads/main
          path: powsybl-core

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          path: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and install powsybl-core with Maven
        run: ./mvnw --batch-mode -DskipTests=true --file ./powsybl-core/pom.xml install

      - name: Build with Maven (Ubuntu / MacOS)
        if: matrix.os != 'windows-latest'
        run: ./mvnw --batch-mode -Pjacoco --file ./main/pom.xml install

      - name: Build with Maven (Windows)
        if: matrix.os == 'windows-latest'
        run: mvnw.cmd --batch-mode --file ./main/pom.xml install
        shell: cmd

      - name: Run SonarCloud analysis
        if: matrix.os == 'ubuntu-latest'
        run: >
          ./mvnw --batch-mode -DskipTests --file ./main/pom.xml sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=com.powsybl:powsybl-open-loadflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
