name: Native build CI

on:
  push:

jobs:
  linux_macos_build:
    name: Build native binary OS (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            name: linux,
            os: ubuntu-latest,
          }
          - {
            name: darwin,
            os: macos-latest,
          }

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Download GraalVM JDK 11
        run: wget -nv https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-${{ matrix.config.name }}-amd64-20.0.0.tar.gz

      - name: Set up GraalVM JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
          jdkFile: graalvm-ce-java11-${{ matrix.config.name }}-amd64-20.0.0.tar.gz

      - name: Fix JAVA_HOME on MacOS
        if: matrix.config.os == 'macos-latest'
        run: mv $JAVA_HOME/Contents/Home/* $JAVA_HOME/

      - name: Install GraalVM Native Image and build with Maven
        run: |
          gu install --no-progress native-image
          mvn --batch-mode -DskipTests=true -Pnative-image package

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: olf
          path: target/olf

  windows_build:
    name: Build native binary OS (windows)
    runs-on: windows-latest
    env:
      VCVARS_BAT: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install GraalVM JDK 11
        run: choco install graalvm --version=20.0.0 --no-progress

      - name: Install GraalVM Native Image and build with Maven
        shell: cmd
        env:
          JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0
        run: |
          call "%JAVA_HOME%\bin\gu" install --no-progress native-image
          copy "%JAVA_HOME%\bin\gu.cmd" "%JAVA_HOME%\bin\gu.exe"
          call "%VCVARS_BAT%"
          call mvn --batch-mode -DskipTests=true -Pnative-image package

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: olf
          path: target/olf
