name: Native build CI

on:
  push:

jobs:
  linux_macos_build:
    name: Build native binary OS (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            name: linux,
            os: ubuntu-latest,
          }
          - {
            name: darwin,
            os: macos-latest,
          }
          - {
            name: windows,
            os: windows-latest,
          }

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Setup GraalVM
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 20.3.0
          native-image: true

      - name: Build with Maven
        run: mvn --batch-mode -DskipTests=true -Pnative-image package

      - name: Build native image
        run: native-image -jar target/powsybl-open-loadflow-*-standalone.jar -H:Name=olf --no-fallback --allow-incomplete-classpath -H:Class=com.powsybl.tools.Main

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: olf-${{ matrix.config.name }}
          path: olf
