name: Native build CI

on:
  push:

jobs:
  build:
    name: Build native binary OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Download GraalVM JDK 11
        run: wget -nv https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-darwin-amd64-20.0.0.tar.gz

      - name: Set up GraalVM JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
          jdkFile: graalvm-ce-java11-darwin-amd64-20.0.0.tar.gz

      - name: Install GraalVM Native Image
        run: gu install --no-progress native-image

      - name: Build with Maven
        run: mvn --batch-mode -DskipTests=true -Pnative-image package

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: olf
          path: target/olf
